-- Migration: Mentor/Student profiles + booking system tables
-- Purpose: Support student dashboard and self-hosted booking (mentor publishes availability)
-- Notes:
--  - UUIDs are generated by the application (Azure Functions), not the DB (pgcrypto not allowed).
--  - Times are stored as timestamptz to avoid timezone errors.
-- Date: 2026-02-08

/* =========================
   1) Profiles: mentors
   ========================= */

CREATE TABLE IF NOT EXISTS mentors (
  mentor_id uuid PRIMARY KEY REFERENCES app_users(user_id) ON DELETE CASCADE,
  display_name text,
  teams_meeting_url text NOT NULL,
  timezone text NOT NULL DEFAULT 'Australia/Brisbane',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE mentors IS
'Mentor profile table. One row per mentor user. Stores persistent Teams link and display preferences.';

COMMENT ON COLUMN mentors.mentor_id IS
'Primary key. Also a foreign key to app_users.user_id for users whose app_role is mentor.';

COMMENT ON COLUMN mentors.display_name IS
'Name shown in the UI. Separate from auth email so mentors can choose preferred name.';

COMMENT ON COLUMN mentors.teams_meeting_url IS
'Persistent Microsoft Teams meeting link used for all sessions. Avoids generating meeting links (cost/complexity).';

COMMENT ON COLUMN mentors.timezone IS
'Timezone used to display times to the mentor (stored times are timestamptz). Default matches org base.';

COMMENT ON COLUMN mentors.created_at IS
'Row creation timestamp for audit/debug.';

COMMENT ON COLUMN mentors.updated_at IS
'Row update timestamp for audit/debug (we can automate updates later with triggers if desired).';


/* =========================
   2) Profiles: students
   ========================= */

CREATE TABLE IF NOT EXISTS students (
  student_id uuid PRIMARY KEY REFERENCES app_users(user_id) ON DELETE CASCADE,
  display_name text,
  grade int,
  timezone text NOT NULL DEFAULT 'Australia/Brisbane',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE students IS
'Student (mentee) profile table. One row per student user. Holds minimal attributes needed for dashboard personalization.';

COMMENT ON COLUMN students.student_id IS
'Primary key. Also a foreign key to app_users.user_id for users whose app_role is mentee.';

COMMENT ON COLUMN students.display_name IS
'Name shown in the UI. Helps avoid showing emails to students.';

COMMENT ON COLUMN students.grade IS
'School grade level used to select weekly curriculum/topic content (e.g., Year 10).';

COMMENT ON COLUMN students.timezone IS
'Timezone used for display to the student (stored times are timestamptz).';

COMMENT ON COLUMN students.created_at IS
'Audit timestamp.';

COMMENT ON COLUMN students.updated_at IS
'Audit timestamp.';


/* ===================================
   3) Mentor ↔ Student assignments
   =================================== */

CREATE TABLE IF NOT EXISTS mentor_assignments (
  mentor_id uuid NOT NULL REFERENCES mentors(mentor_id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','ended')),
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  PRIMARY KEY (mentor_id, student_id)
);

COMMENT ON TABLE mentor_assignments IS
'Relationship table linking mentors to students. Supports 1 mentor → many students now, and allows history when pairings change.';

COMMENT ON COLUMN mentor_assignments.mentor_id IS
'Assigned mentor. Many rows can share the same mentor_id (mentor has multiple students).';

COMMENT ON COLUMN mentor_assignments.student_id IS
'Assigned student. Typically has one active mentor at a time (enforced by partial unique index below).';

COMMENT ON COLUMN mentor_assignments.status IS
'Assignment lifecycle. active = current pairing; ended = historical pairing.';

COMMENT ON COLUMN mentor_assignments.started_at IS
'When the pairing became active (for reporting and timeline).';

COMMENT ON COLUMN mentor_assignments.ended_at IS
'When the pairing ended (nullable).';

-- Enforce: one active mentor per student (but allow history)
CREATE UNIQUE INDEX IF NOT EXISTS uq_one_active_mentor_per_student
ON mentor_assignments(student_id)
WHERE status = 'active';

COMMENT ON INDEX uq_one_active_mentor_per_student IS
'Ensures each student has at most one active mentor at a time, while preserving ended history.';

-- Helpful query index (find active mentor for student quickly)
CREATE INDEX IF NOT EXISTS idx_mentor_assignments_student_active
ON mentor_assignments(student_id)
WHERE status = 'active';


/* ===================================
   4) Mentor availability slots
   =================================== */

CREATE TABLE IF NOT EXISTS mentor_availability_slots (
  slot_id uuid PRIMARY KEY,
  mentor_id uuid NOT NULL REFERENCES mentors(mentor_id) ON DELETE CASCADE,
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'available'
    CHECK (status IN ('available','booked','cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (end_time > start_time)
);

COMMENT ON TABLE mentor_availability_slots IS
'Mentor-published availability. Students book from these slots (Option A booking model).';

COMMENT ON COLUMN mentor_availability_slots.slot_id IS
'Primary key UUID generated by API. DB-side UUID extensions are restricted in Azure.';

COMMENT ON COLUMN mentor_availability_slots.mentor_id IS
'Owner of the availability slot. Drives filtering in UI and permission checks in API.';

COMMENT ON COLUMN mentor_availability_slots.start_time IS
'Slot start time stored with timezone (timestamptz) to avoid DST/timezone bugs.';

COMMENT ON COLUMN mentor_availability_slots.end_time IS
'Slot end time. Must be greater than start_time.';

COMMENT ON COLUMN mentor_availability_slots.status IS
'Slot state: available (bookable), booked (reserved by a confirmed booking), cancelled (withdrawn by mentor).';

COMMENT ON COLUMN mentor_availability_slots.created_at IS
'Audit timestamp.';

COMMENT ON COLUMN mentor_availability_slots.updated_at IS
'Audit timestamp.';

CREATE INDEX IF NOT EXISTS idx_slots_mentor_start_available
ON mentor_availability_slots(mentor_id, start_time)
WHERE status = 'available';

COMMENT ON INDEX idx_slots_mentor_start_available IS
'Speeds up listing upcoming available slots for a given mentor.';


/* =========================
   5) Bookings
   ========================= */

CREATE TABLE IF NOT EXISTS bookings (
  booking_id uuid PRIMARY KEY,
  slot_id uuid NOT NULL UNIQUE
    REFERENCES mentor_availability_slots(slot_id) ON DELETE RESTRICT,
  mentor_id uuid NOT NULL REFERENCES mentors(mentor_id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,

  status text NOT NULL DEFAULT 'requested'
    CHECK (status IN ('requested','confirmed','cancelled')),

  note text,

  requested_at timestamptz NOT NULL DEFAULT now(),
  confirmed_at timestamptz,
  cancelled_at timestamptz,
  cancelled_by text CHECK (cancelled_by IN ('student','mentor')),

  meeting_url_snapshot text,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE bookings IS
'Booking records created when a student selects a mentor availability slot. Used for upcoming sessions and email notifications.';

COMMENT ON COLUMN bookings.booking_id IS
'Primary key UUID generated by API.';

COMMENT ON COLUMN bookings.slot_id IS
'FK to mentor_availability_slots. UNIQUE enforces one booking per slot (prevents double booking).';

COMMENT ON COLUMN bookings.mentor_id IS
'Redundant FK to mentor for fast queries and permission checks (avoids joins in common endpoints). Must match slot mentor_id in API.';

COMMENT ON COLUMN bookings.student_id IS
'Student who requested the booking. Powers student dashboard upcoming sessions.';

COMMENT ON COLUMN bookings.status IS
'Booking lifecycle: requested (student submitted), confirmed (mentor approved), cancelled.';

COMMENT ON COLUMN bookings.note IS
'Optional student note: what they want help with. Included in confirmation email.';

COMMENT ON COLUMN bookings.requested_at IS
'When the student created the booking request.';

COMMENT ON COLUMN bookings.confirmed_at IS
'When mentor confirmed. Confirmation triggers email notification.';

COMMENT ON COLUMN bookings.cancelled_at IS
'When booking was cancelled.';

COMMENT ON COLUMN bookings.cancelled_by IS
'Who cancelled (student or mentor). Useful for reporting and support.';

COMMENT ON COLUMN bookings.meeting_url_snapshot IS
'Copy of mentor Teams link captured at confirmation time. Preserves history if mentor later changes their link.';

COMMENT ON COLUMN bookings.created_at IS
'Audit timestamp.';

COMMENT ON COLUMN bookings.updated_at IS
'Audit timestamp.';

CREATE INDEX IF NOT EXISTS idx_bookings_student_recent
ON bookings(student_id, requested_at DESC);

COMMENT ON INDEX idx_bookings_student_recent IS
'Speeds up student dashboard view of recent/pending/confirmed bookings.';

CREATE INDEX IF NOT EXISTS idx_bookings_mentor_recent
ON bookings(mentor_id, requested_at DESC);

COMMENT ON INDEX idx_bookings_mentor_recent IS
'Speeds up mentor dashboard view of pending requests and upcoming bookings.';

CREATE INDEX IF NOT EXISTS idx_bookings_status
ON bookings(status);

COMMENT ON INDEX idx_bookings_status IS
'Speeds up filtering by booking status (requested vs confirmed).';


--link app users yo student and mentor tables

ALTER TABLE mentors
ADD COLUMN IF NOT EXISTS user_id uuid;

ALTER TABLE students
ADD COLUMN IF NOT EXISTS user_id uuid;

ALTER TABLE mentors
ADD CONSTRAINT  mentors_user_id_fk
FOREIGN KEY (user_id) REFERENCES app_users(user_id);

ALTER TABLE students
ADD CONSTRAINT  students_user_id_fk
FOREIGN KEY (user_id) REFERENCES app_users(user_id);

-- testing queries

/*SELECT
  booking_id,
  status,
  confirmed_at,
  meeting_url_snapshot
FROM bookings
WHERE booking_id = '33333333-3333-3333-3333-333333333333';

DELETE FROM bookings
WHERE slot_id = '22222222-2222-2222-2222-222222222222';

UPDATE bookings
SET status = 'requested',
    confirmed_at = NULL
WHERE booking_id = '33333333-3333-3333-3333-333333333333';

**/

select* from students s 

SELECT
  b.booking_id,
  b.status,
  m.display_name AS mentor_name,
  au_m.email     AS mentor_email,
  s.display_name AS student_name,
  au_s.email     AS student_email,
  b.confirmed_at
FROM bookings b
JOIN mentors m       ON m.mentor_id = b.mentor_id
JOIN students s      ON s.student_id = b.student_id
LEFT JOIN app_users au_m ON au_m.user_id = m.mentor_id
LEFT JOIN app_users au_s ON au_s.user_id = s.student_id
WHERE b.booking_id = '33333333-3333-3333-3333-333333333333';


